wallpaper {
	monitor = eDP-1 # Leaving monitor empty, like "monitor = ", applies this to all detected outputs
	path = /home/dalter124/Gallery/Wallpapers/black_hole.png
	fit_mode = cover
}

# Uncomment if using multi-monitor setup:
# wallpaper {
# monitor = $second
# path = ~/.config/hypr/walls/
# fit_mode = cover
# timeout = $timeout
# }
# wallpaper {
# monitor = $third
# path = ~/.config/hypr/walls/
# fit_mode = cover
# timeout = $timeout
# }

splash = true



